default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5432
  username: postgres
  password: Admin123

development:
  <<: *default
  database: BookFlix_development

test:
  <<: *default
  database: BookFlix_test

production:
  <<: *default
  database: BookFlix_production
  username: BookFlix
  password: <%= ENV["BookFlix_DATABASE_PASSWORD"] %>
